version: '3.7'
# ====================================== AIRFLOW ENVIRONMENT VARIABLES =======================================
x-environment: &airflow_environment
  # Airflow settings.
  - AIRFLOW__CORE__EXECUTOR=LocalExecutor
  - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
  - AIRFLOW__CORE__LOAD_EXAMPLES=False
  - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://postgres:postgres@postgres:5432/airflow
  - AIRFLOW__CORE__STORE_DAG_CODE=True
  - AIRFLOW__CORE__STORE_SERIALIZED_DAGS=True
  - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
  - AIRFLOW__WEBSERVER__RBAC=False
  # Movielens API settings.
  - AIRFLOW_CONN_MOVIEREC=http://airflow:airflow@movierec
  - MOVIEREC_USER=airflow
  - MOVIEREC_PASSWORD=airflow
x-airflow-image: &airflow_image apache/airflow:2.5.0-python3.8
# ====================================== /AIRFLOW ENVIRONMENT VARIABLES ======================================
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
  init:
    build:
      context: docker/airflow-data
      args:
        AIRFLOW_BASE_IMAGE: *airflow_image
    image: manning-airflow/airflow-data
    depends_on:
      - postgres
    environment: *airflow_environment
    entrypoint: /bin/bash
    command: -c 'airflow db upgrade && sleep 5 && airflow users create --username admin --password admin --firstname Anonymous --lastname Admin --role Admin --email admin@example.org'
  webserver:
    build:
      context: docker/airflow-data
      args:
        AIRFLOW_BASE_IMAGE: *airflow_image
    image: manning-airflow/airflow-data
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - logs:/opt/airflow/logs
    environment: *airflow_environment
    command: webserver
  scheduler:
    build:
      context: docker/airflow-data
      args:
        AIRFLOW_BASE_IMAGE: *airflow_image
    image: manning-airflow/airflow-data
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - data:/data
      - logs:/opt/airflow/logs
    environment: *airflow_environment
    command: scheduler
  movierec:
    build: docker/movierec-api
    image: manning-airflow/movierec-api
    ports:
      - "5000:5000"
    environment:
      API_USER: airflow
      API_PASSWORD: airflow

volumes:
  data:
  logs: